collections:
  category:
    output: true
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "category"
    values:
      layout: "category"
      permalink: /category/:name
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: /posts/:title
