paginate: 5
paginate_path: "/page:num"

collections:
  category:
    output: true
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "category"
    values:
      layout: "category"
      permalink: /category/:name
      c_paginate_path: /category/:name/:num
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: /posts/:title

plugins:
  - jekyll-paginate
